config/routes.rb
Rails.application.routes.draw do
 
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self) 
  class ActiveAdmin::Devise::SessionsController 
   before_action :auth_user
 def auth_user
  return if current_user.try(:admin?) == true

    redirect_to home_About_path

  end
end
  resources :measurments
  resources :personal_trainers
  resources :pt_clients
  resources :gym_classes
  devise_for :users, controllers: { registrations: "users/registrations" }
  #get 'home/index'
  get 'home/PersonalTrainer'
  get 'home/About'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.onrg/routing.html
end

app/models/pt_client.rb
class PtClient < ApplicationRecord
	belongs_to :personal_trainer
end

app/controllers/pt_clients_controller.rb
class PtClientsController < ApplicationController
  before_action :set_pt_client, only: %i[ show edit update destroy ]

  # GET /pt_clients or /pt_clients.json
  def index
    @pt_clients = PtClient.all
  end

  # GET /pt_clients/1 or /pt_clients/1.json
  def show
  end

  # GET /pt_clients/new
  def new
    @pt_client = PtClient.new
  end

  # GET /pt_clients/1/edit
  def edit
  end

  # POST /pt_clients or /pt_clients.json
  def create
    @pt_client = PtClient.new(pt_client_params)

    respond_to do |format|
      if @pt_client.save
        format.html { redirect_to @pt_client, notice: "Pt client was successfully created." }
        format.json { render :show, status: :created, location: @pt_client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pt_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pt_clients/1 or /pt_clients/1.json
  def update
    respond_to do |format|
      if @pt_client.update(pt_client_params)
        format.html { redirect_to @pt_client, notice: "Pt client was successfully updated." }
        format.json { render :show, status: :ok, location: @pt_client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pt_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pt_clients/1 or /pt_clients/1.json
  def destroy
    @pt_client.destroy
    respond_to do |format|
      format.html { redirect_to pt_clients_url, notice: "Pt client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pt_client
      @pt_client = PtClient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pt_client_params
      params.require(:pt_client).permit(:name, :age, :email, :number)
    end
end

app/helpers/pt_clients_helper.rb
module PtClientsHelper
end

app/views/pt_clients/_form.html.erb
<%= form_with(model: pt_client) do |form| %>
  <% if pt_client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pt_client.errors.count, "error") %> prohibited this pt_client from being saved:</h2>

      <ul>
        <% pt_client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pt_clients/edit.html.erb
<h1>Editing Pt Client</h1>

<%= render 'form', pt_client: @pt_client %>

<%= link_to 'Show', @pt_client %> |
<%= link_to 'Back', pt_clients_path %>

app/views/pt_clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pt Clients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th>Email</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pt_clients.each do |pt_client| %>
      <tr>
        <td><%= pt_client.name %></td>
        <td><%= pt_client.age %></td>
        <td><%= pt_client.email %></td>
        <td><%= pt_client.number %></td>
        <td><%= link_to 'Show', pt_client %></td>
        <td><%= link_to 'Edit', edit_pt_client_path(pt_client) %></td>
        <td><%= link_to 'Destroy', pt_client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pt Client', new_pt_client_path %>

app/views/pt_clients/new.html.erb
<h1>New Pt Client</h1>

<%= render 'form', pt_client: @pt_client %>

<%= link_to 'Back', pt_clients_path %>

app/views/pt_clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pt_client.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @pt_client.age %>
</p>

<p>
  <strong>Email:</strong>
  <%= @pt_client.email %>
</p>

<p>
  <strong>Number:</strong>
  <%= @pt_client.number %>
</p>

<%= link_to 'Edit', edit_pt_client_path(@pt_client) %> |
<%= link_to 'Back', pt_clients_path %>