config/routes.rb
Rails.application.routes.draw do
 
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self) 
  class ActiveAdmin::Devise::SessionsController 
   before_action :auth_user
 def auth_user
  return if current_user.try(:admin?) == true

    redirect_to home_About_path

  end
end
  resources :measurments
  resources :personal_trainers
  resources :pt_clients
  resources :gym_classes
  devise_for :users, controllers: { registrations: "users/registrations" }
  #get 'home/index'
  get 'home/PersonalTrainer'
  get 'home/About'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.onrg/routing.html
end

app/models/personal_trainer.rb
class PersonalTrainer < ApplicationRecord
	has_many :gym_classes
	has_many :pt_clients
end

app/controllers/personal_trainers_controller.rb
require './app/policies/personal_trainer_policy'
class PersonalTrainersController < ApplicationController
  before_action :set_personal_trainer, only: %i[ show edit update destroy ]
  before_action :auth_user, :except => [:show, :index]
  

  # GET /personal_trainers or /personal_trainers.json
  def index
    @personal_trainers = PersonalTrainer.all
  end

  # GET /personal_trainers/1 or /personal_trainers/1.json
  def show
  end

  # GET /personal_trainers/new
  def new
    
    @personal_trainer = PersonalTrainer.new

  end
  def auth_user
      return if current_user.admin == true

          redirect_to personal_trainers_path, notice: "Must be admin"
     end

  # GET /personal_trainers/1/edit
  def edit
  end

  # POST /personal_trainers or /personal_trainers.json
  def create
    @personal_trainer = PersonalTrainer.new(personal_trainer_params)
    authorize @personal_trainer
    respond_to do |format|
      if @personal_trainer.save
        format.html { redirect_to @personal_trainer, notice: "Personal trainer was successfully created." }
        format.json { render :show, status: :created, location: @personal_trainer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @personal_trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personal_trainers/1 or /personal_trainers/1.json
  def update
    authorize @personal_trainer
    respond_to do |format|
      if @personal_trainer.update(personal_trainer_params)
        format.html { redirect_to @personal_trainer, notice: "Personal trainer was successfully updated." }
        format.json { render :show, status: :ok, location: @personal_trainer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @personal_trainer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personal_trainers/1 or /personal_trainers/1.json
  def destroy
    authorize @personal_trainer
    @personal_trainer.destroy
    respond_to do |format|
      format.html { redirect_to personal_trainers_url, notice: "Personal trainer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_personal_trainer
      @personal_trainer = PersonalTrainer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def personal_trainer_params
      params.require(:personal_trainer).permit(:name, :email, :number, :description, :noOfClient)
    end
end

app/helpers/personal_trainers_helper.rb
module PersonalTrainersHelper
end

app/views/personal_trainers/_form.html.erb
<%= stylesheet_link_tag 'show', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4", style="text-align: center;">
      
       Personal Trainer
    </h1>
<%= form_with(model: personal_trainer) do |form| %>
  <% if personal_trainer.errors.any? %>
  

      <ul>
        <% personal_trainer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :noOfClient %>
    <%= form.number_field :noOfClient %>
  </div>

  <div class="actions", style="text-align:center;">
    <%= form.submit %>
  </div>
<% end %>
</div>
</div>

app/views/personal_trainers/edit.html.erb
<%= render 'form', personal_trainer: @personal_trainer %>

<%= link_to 'Show', @personal_trainer, class:"btn btn-dark"  %> |
<%= link_to 'Back', personal_trainers_path, class:"btn btn-dark"  %>

app/views/personal_trainers/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">Personal Trainers</h1>

<div class = "page-conatiner">
<table class = "table table-striped table-hover table-bordered">
  <thead class="table-dark">    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Number</th>
      <th>Description</th>
      <th>Noofclient</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @personal_trainers.each do |personal_trainer| %>
      <tr>
        <td><%= personal_trainer.name %></td>
        <td><%= personal_trainer.email %></td>
        <td><%= personal_trainer.number %></td>
        <td><%= personal_trainer.description %></td>
        <td><%= personal_trainer.noOfClient %></td>
        <td><%= link_to 'Show', personal_trainer %></td>
        <% if signed_in? %>
          <% if current_user.admin == true %>
        <td><%= link_to 'Edit', edit_personal_trainer_path(personal_trainer) %></td>
        <td><%= button_to  'Destroy', personal_trainer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Personal Trainer', new_personal_trainer_path, class:"btn btn-dark" %>
</div>

app/views/personal_trainers/new.html.erb
<%= render 'form', personal_trainer: @personal_trainer %>

<%= link_to 'Back', personal_trainers_path, class:"btn btn-dark" %>

app/views/personal_trainers/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">
      <%= @personal_trainer.name %>
      
    </h1>

<p>
  <strong>Email:</strong>
  <%= @personal_trainer.email %>
</p>

<p>
  <strong>Number:</strong>
  <%= @personal_trainer.number %>
</p>

<p>
  <strong>Description:</strong>
  <%= @personal_trainer.description %>
</p>

<p>
  <strong>Noofclient:</strong>
  <%= @personal_trainer.noOfClient %>
</p>
 </div>
</div>

<%= link_to 'Edit', edit_personal_trainer_path(@personal_trainer), class:"btn btn-dark" %> |
<%= link_to 'Back', personal_trainers_path, class:"btn btn-dark" %>