config/routes.rb
Rails.application.routes.draw do
 
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self) 
  class ActiveAdmin::Devise::SessionsController 
   before_action :auth_user
 def auth_user
  return if current_user.try(:admin?) == true

    redirect_to home_About_path

  end
end
  resources :measurments
  resources :personal_trainers
  resources :pt_clients
  resources :gym_classes
  devise_for :users, controllers: { registrations: "users/registrations" }
  #get 'home/index'
  get 'home/PersonalTrainer'
  get 'home/About'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.onrg/routing.html
end

app/controllers/gym_classes_controller.rb
require './app/policies/gym_class_policy'
class GymClassesController < ApplicationController
  before_action :set_gym_class, only: %i[ show edit update destroy ]
  before_action :auth_user, :except => [:show, :index]

  # GET /gym_classes or /gym_classes.json
  def index
    @gym_classes = GymClass.all
  end

  # GET /gym_classes/1 or /gym_classes/1.json
  def show
  end

  # GET /gym_classes/new
  def new
    @gym_class = GymClass.new
  end
  def auth_user
      return if current_user.admin == true

          redirect_to personal_trainers_path, notice: "Must be admin"
     end

  # GET /gym_classes/1/edit
  def edit
  end

  # POST /gym_classes or /gym_classes.json
  def create
    
    @gym_class = GymClass.new(gym_class_params)
    authorize @gym_class

    respond_to do |format|
      if @gym_class.save
        format.html { redirect_to @gym_class, notice: "Gym class was successfully created." }
        format.json { render :show, status: :created, location: @gym_class }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gym_class.errors, status: :unprocessable_entity }
      end
    end
    
  end

  # PATCH/PUT /gym_classes/1 or /gym_classes/1.json
  def update
    authorize @gym_class
    respond_to do |format|
      if @gym_class.update(gym_class_params)
        format.html { redirect_to @gym_class, notice: "Gym class was successfully updated." }
        format.json { render :show, status: :ok, location: @gym_class }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gym_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gym_classes/1 or /gym_classes/1.json
  def destroy
    authorize @gym_class
    @gym_class.destroy
    respond_to do |format|
      format.html { redirect_to gym_classes_url, notice: "Gym class was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gym_class
      @gym_class = GymClass.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gym_class_params
      params.require(:gym_class).permit(:PT_id, :PT_name, :Class_type, :Date, :Time)
    end
end

app/helpers/gym_classes_helper.rb
module GymClassesHelper
end

app/views/gym_classes/_form.html.erb
<p id="notice"><%= notice %></p>

<%= stylesheet_link_tag 'show', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4", style="text-align: center;">
      
      New Gym Class
    </h1>
        <%= form_with(model: gym_class) do |form| %>
  <% if gym_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gym_class.errors.count, "error") %> prohibited this gym_class from being saved:</h2>

      <ul>
        <% gym_class.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :PT_id %>
    <%= form.number_field :PT_id %>
  </div>

  <div>
    <%= form.label :PT_name %>
    <%= form.text_field :PT_name%>
  </div>

  <div>
    <%= form.label :Class_type %>
    <%= form.text_field :Class_type %>
  </div>

  <div>
    <%= form.label :Date %>
    <%= form.date_select :Date %>
  </div>

  <div>
    <%= form.label :Time %>
    <%= form.time_select :Time %>
  </div>

  <div class="actions", style="text-align:center;">
    <%= form.submit %>
  </div>
<% end %>

   
  </div>
</div>

app/views/gym_classes/edit.html.erb
<%= render 'form', gym_class: @gym_class %>

<%= link_to 'Show', @gym_class, class:"btn btn-dark" %> |
<%= link_to 'Back', gym_classes_path, class:"btn btn-dark" %>

app/views/gym_classes/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">Gym Classes</h1>
<div class = "page-conatiner">
<table class = "table table-striped table-hover table-bordered">
  <thead class="table-dark">
    <tr> 
      <th>PT ID</th>
      <th>PT name</th>
      <th>Class</th>
      <th>Date</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gym_classes.each do |gym_class| %>
      <tr>
        <td><%= gym_class.PT_id %></td>
        <td><%= gym_class.PT_name %></td>
        <td><%= gym_class.Class_type %></td>
        <td><%= gym_class.Date %></td>
        <td><%= gym_class.Time %></td>
        <td><%= link_to 'Show', gym_class %></td>
        <% if signed_in? %>
          <% if current_user.admin == true %>
        <td><%= link_to 'Edit', edit_gym_class_path(gym_class) %></td>
        <td><%= button_to  'Destroy', gym_class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

    <%= link_to 'New Gym Class', new_gym_class_path, class:"btn btn-dark" %>
  
</div>

app/views/gym_classes/new.html.erb
<%= render 'form', gym_class: @gym_class %>

<%= link_to 'Back', gym_classes_path, class:"btn btn-dark" %>

app/views/gym_classes/show.html.erb
<p id="notice"><%= notice %></p>

<%= stylesheet_link_tag 'show', media: 'all', 'data-turbolinks-track': 'reload' %>
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">
      <%= @gym_class.PT_name %>
      
    </h1>
    <p>
  <strong>Class type:</strong>
  <%= @gym_class.Class_type %>
</p>

<p>
  <strong>Date:</strong>
  <%= @gym_class.Date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @gym_class.Time %>
</p>
    <%= link_to 'Edit', edit_gym_class_path(@gym_class), class:"btn btn-dark"  %> |
    <%= link_to 'Back', gym_classes_path, class:"btn btn-dark"  %>
  </div>
</div>