config/routes.rb
Rails.application.routes.draw do
 
  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self) 
  class ActiveAdmin::Devise::SessionsController 
   before_action :auth_user
 def auth_user
  return if current_user.try(:admin?) == true

    redirect_to home_About_path

  end
end
  resources :measurments
  resources :personal_trainers
  resources :pt_clients
  resources :gym_classes
  devise_for :users, controllers: { registrations: "users/registrations" }
  #get 'home/index'
  get 'home/PersonalTrainer'
  get 'home/About'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.onrg/routing.html
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <title>Gym App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
      <%= link_to 'GYM APP' , root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to 'Home' , root_path, class:"navbar-brand" %>
        </li>
        <li class="nav-item">
        <%= link_to 'About' , home_About_path, class:"navbar-brand" %>
        </li>

        <li class="nav-item">
        <%= link_to 'Classes' , gym_classes_path, class:"navbar-brand" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Personal Trainer' , personal_trainers_path, class:"navbar-brand" %>
        </li>
        <% if signed_in? %>
          <%= link_to 'Measurments' , measurments_path, class:"navbar-brand" %>
         
          <%= link_to "Profile", edit_user_registration_path, class:"navbar-brand" %>
         
          <% if current_user.admin == true %>
            <li class="nav-item">
            <%= link_to 'Admin' , new_admin_user_session_path, class:"navbar-brand" %>       
            </li>
         <% end %>
        <% end %>
       
    
      </ul>
      <% if signed_in? %>
       <%= button_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link", id:"signOut" %>

     <% else %>
     <li class="nav-item">
        <%= link_to "Login", new_user_session_path, id:"signIN" %>
     </li>
     <li class="nav-item">
        <%= link_to 'Sign up', new_user_registration_path, id:"register" %>
     </li>
     </ul>
    <% end %>
    </div>
  </div>
</nav>
    <%= yield %>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
  </body>
</html>